-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 19:08:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estudosql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estudosql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudosql` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `estudosql` ;

-- -----------------------------------------------------
-- Table `estudosql`.`tipo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudosql`.`tipo_cliente` (
  `i_tipocliente_tipocliente` INT NOT NULL AUTO_INCREMENT,
  `s_dectipocliente_tipocliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`i_tipocliente_tipocliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `estudosql`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudosql`.`cliente` (
  `i_cliente_cliente` INT NOT NULL,
  `s_nome_cliente` VARCHAR(50) NOT NULL,
  `s_cpf_cliente` CHAR(11) NOT NULL,
  `d_nasc_cliente` DATETIME NULL DEFAULT NULL,
  `i_idade_cliente` TINYINT NULL DEFAULT NULL,
  `i_tipo_cliente` INT NOT NULL DEFAULT NULL,
  PRIMARY KEY (`i_cliente_cliente`),
  INDEX `fk_tipocliente` (`i_tipo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tipocliente`
    FOREIGN KEY (`i_tipo_cliente`)
    REFERENCES `estudosql`.`tipo_cliente` (`i_tipocliente_tipocliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--Salvamento criado pelo MySQL através do relacionamento de diagrama